name = "efhsband"
main = "worker/src/worker.mjs"
compatibility_date = "2026-07-29"
account_id = "d4e69b2379a7e3c86020154cf70a1d07"
workers_dev = true

[assets]
directory = "./assets"
binding = "ASSETS"

[vars]
EFBAND_ADMIN_USERNAME = "admin"
EFBAND_ADMIN_PASSWORD = "admin123$"
CONTACT_FROM_EMAIL = "noreply@efhsband.org"
CONTACT_FROM_NAME = "East Forsyth Band Website"
CONTACT_DEFAULT_EMAIL = ""
CONTACT_EMAIL_PROVIDER = "formsubmit"

[[d1_databases]]
binding = "DB"
database_name = "efhsband-db"
database_id = "73681cba-4863-4abb-86d4-b140694bcde2"
